wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# https://esphome.io/components/ota.html#updating-the-password
ota:
  safe_mode: true
  password: !secret ota_password

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
