substitutions:
  name: ratgdo-4b0f45
  friendly_name: Ratgdo Garage

packages:
  jacobfg.upsy-desky: github://jacobfg/esphome/ratgdov25i.yaml@devel

api:
  encryption:
    key: ""

<<: !include .wifi.yaml
