substitutions:
  name: tagreader-d6646f
  friendly_name: Tag Reader Office

packages:
  jacobfg.tagreader: github://jacobfg/esphome/tagreader.yaml@devel

api:
  encryption:
    key: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# move below to common file ?
# https://esphome.io/components/ota.html#updating-the-password
ota:
  safe_mode: true
  password: !secret ota_password

captive_portal: !remove
dashboard_import: !remove

logger:
  level: ERROR
