substitutions:
  name: tagreader-dbb270
  friendly_name: Tag Reader Alice

packages:
  jacobfg.tagreader: github://jacobfg/esphome/tagreader.yaml@devel

api:
  encryption:
    key: ""

<<: !include .wifi.yaml
