substitutions:
  name: upsy-desky-76dc10
  friendly_name: Upsy Desky Office

packages:
  jacobfg.upsy-desky: github://jacobfg/esphome/upsy-desky.yaml@devel

api:
  encryption:
    key: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# move below to common file ?
# https://esphome.io/components/ota.html#updating-the-password
ota:
  safe_mode: true
  password: !secret ota_password

captive_portal: !remove
web_server: !remove
dashboard_import: !remove
