substitutions:
  name: upsy-desky-76dc10
  friendly_name: Upsy Desky Office

packages:
  jacobfg.upsy-desky: github://jacobfg/esphome/upsy-desky.yaml@devel

api:
  encryption:
    key: ""

<<: !include .wifi.yaml
